# Generated by Django 2.2.4 on 2022-06-07 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20220608_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joined_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Group')),
            ],
        ),
    ]
