# Generated by Django 2.2.4 on 2022-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='email',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
