# Generated by Django 2.2.4 on 2022-06-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20220611_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='blog',
            new_name='post',
        ),
    ]
