# Generated by Django 2.2.4 on 2022-06-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
