# Generated by Django 2.2.4 on 2022-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_remove_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
